version: "3"
services:

  sar-db-renderer:
    image: postgres:15
    networks:
      - hmpps
    container_name: sar-db-renderer
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=admin_password
      - POSTGRES_USER=admin
      - POSTGRES_DB=sar-db-renderer

  localstack:
    image: localstack/localstack:3
    networks:
      - hmpps
    container_name: localstack-pl
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"

  wiremock:
    image: wiremock/wiremock
    networks:
      - hmpps
    container_name: wiremock
    restart: always
    ports:
      - "9091:8080"
    volumes:
     - ./wiremock/mappings:/home/wiremock/mappings
     - ./wiremock/__files:/home/wiremock/__files

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth
    ports:
      - "9090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0
      - SYSTEM_CLIENT_ID=hmpps-integration-api-client
      - SYSTEM_CLIENT_SECRET=clientsecret

networks:
  hmpps: