hmpps-auth:
  url: "http://localhost:8080/auth"
  ## url: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
locations-api:
  url: http://localhost:8085
nomis-mappings-api:
  url: http://localhost:8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sar-db?sslmode=prefer
    username: admin
    password: admin_password
  flyway:
    locations: classpath:db/sar,db/sar_{vendor},db/dev/data/sar
    enabled: true
    url: jdbc:postgresql://localhost:5432/sar-db?sslmode=prefer
    user: admin
    password: admin_password

  security:
    oauth2:
      client:
        registration:
          sar-html-renderer-client:
            provider: hmpps-auth
            client-id: "hmpps-subject-access-request-html-renderer"
            client-secret: ""
            authorization-grant-type: client_credentials
            scope: read

s3:
  provider: localstack
  region: eu-west-2
  serviceEndpointOverride: http://localhost:4566
  bucket-name: subject-access-request-html

developer-endpoint:
  enabled: true