info.app:
  name: HMPPS Subject Access Request Html Renderer
  version: 1.0

spring:
  application:
    name: hmpps-subject-access-request-html-renderer
  codec:
    max-in-memory-size: 10MB

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  flyway:
    enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${hmpps-auth.url}/.well-known/jwks.json

      # TODO: This client section can be removed if your service doesn't call out to other services
      client:
        provider:
          hmpps-auth:
            token-uri: ${hmpps-auth.url}/oauth/token

        registration:
          sar-html-renderer-client:
            provider: hmpps-auth
            client-id: ${system.client.id}
            client-secret: ${system.client.secret}
            authorization-grant-type: client_credentials
            scope: read

  datasource:
    url: 'jdbc:postgresql://${DATABASE_ENDPOINT}/${DATABASE_NAME}?sslmode=verify-full'
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  profiles:
    group:
      dev:
        - "dev"

server:
  port: 8090
  servlet:
    context-path: /
  forward-headers-strategy: native
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
      internal-proxies: 10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|169\.254\.\d{1,3}\.\d{1,3}|127\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.1[6-9]{1}\.\d{1,3}\.\d{1,3}|172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}|172\.3[0-1]{1}\.\d{1,3}\.\d{1,3}|0:0:0:0:0:0:0:1|::1|100\.6[4-9]\.\d{1,3}\.\d{1,3}|100\.[7-9][0-9]{1}\.\d{1,3}\.\d{1,3}|100\.1[0-1][0-9]{1}\.\d{1,3}\.\d{1,3}|100\.12[0-7]\.\d{1,3}\.\d{1,3}
  shutdown: graceful
  error:
    include-message: always

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info, health'
  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-components: always
      show-details: always
      probes:
        enabled: true
    info:
      cache:
        time-to-live: 2000ms

web-client:
  configuration:
    max-retries: 2
    back-off: PT10S

template-resources:
  directory: /templates

s3:
  provider: aws
  region: eu-west-1
  serviceEndpointOverride: http://localhost:4566
  bucket-name: hmpps-subject-access-request_s3_bucket