hmpps-auth:
  url: "http://localhost:8090/auth"

spring:
  security:
    oauth2:
      client:
        registration:
          sar-html-renderer-client:
            provider: hmpps-auth
            client-id: "hmpps-subject-access-request-html-renderer"
            client-secret: "clientsecret"
            authorization-grant-type: client_credentials
            scope: read