---
# Per environment values which override defaults in hmpps-subject-access-request-html-renderer/values.yaml

generic-service:
  replicaCount: 4

  ingress:
    host: subject-access-request-html-renderer.hmpps.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    LOCATIONS_API_URL: "https://locations-inside-prison-api.hmpps.service.justice.gov.uk"
    NOMIS_MAPPINGS_API_URL: "https://nomis-sync-prisoner-mapping.hmpps.service.justice.gov.uk"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps_tech
