---
# Per environment values which override defaults in hmpps-subject-access-request-html-renderer/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: subject-access-request-html-renderer-preprod.hmpps.service.justice.gov.uk
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    LOCATIONS_API_URL: "https://locations-inside-prison-api-preprod.hmpps.service.justice.gov.uk"
    NOMIS_MAPPINGS_API_URL: "https://nomis-sync-prisoner-mapping-preprod.hmpps.service.justice.gov.uk"
    SUBJECT_ACCESS_REQUEST_API_URL: "https://subject-access-request-api-preprod.hmpps.service.justice.gov.uk"
    DEVELOPER_ENDPOINT_ENABLED: false
    WEB_CLIENT_CONFIGURATION_BACK_OFF: "PT1M"
    API_TIMEOUT: "600s"
    TEMPLATE_HELPER_CACHE_MAXIMUM_SIZE: 50000
    TEMPLATE_HELPER_CACHE_EXPIRE_AFTER_MINUTES: 50

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
